//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace InformationSystem.App.Resources.Texts {
    using System;


    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class RoomText {

        private static System.Resources.ResourceManager resourceMan;

        private static System.Globalization.CultureInfo resourceCulture;

        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal RoomText() {
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("InformationSystem.App.Resources.Texts.RoomText", typeof(RoomText).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }

        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }

        internal static string A1 {
            get {
                return ResourceManager.GetString("A1", resourceCulture);
            }
        }

        internal static string A2 {
            get {
                return ResourceManager.GetString("A2", resourceCulture);
            }
        }

        internal static string A3 {
            get {
                return ResourceManager.GetString("A3", resourceCulture);
            }
        }

        internal static string A4 {
            get {
                return ResourceManager.GetString("A4", resourceCulture);
            }
        }

        internal static string A5 {
            get {
                return ResourceManager.GetString("A5", resourceCulture);
            }
        }

        internal static string None {
            get {
                return ResourceManager.GetString("None", resourceCulture);
            }
        }
    }
}
